wafflestudio/internhasha-web

- src/mocks/auth/handlers.ts
- src/mocks/auth/resolvers.ts
- src/mocks/auth/schemas.ts
- src/pages/EmailVerifyPage/EmailVerifyForm.tsx
- src/pages/LocalSignUpPage/LocalSignUpForm.tsx
- src/pages/SignUpSelectPage/GoogleSocialSignUpButton.tsx
- src/presentation/authPresentation.ts
- src/service/authService.ts
- src/shared/api/api.ts
- src/shared/api/entities/schemas.ts
- src/shared/route/useRouteNavigation.ts
로컬 회원가입 시 유저 플로우를 API 및 화면 명세에 맞게 수정합니다.
- 실명, 아이디, 비밀번호, 비밀번호 확인 필드가 나타납니다.
- 아이디 중복 확인을 하지 않으면 다음 단계로 넘어가지 않습니다.
- 중복 인증 시 중복 확인 버튼이 사라집니다.
- 이후 다음을 누르면 이메일 인증 페이지로 넘어갑니다.
> ✨ 로컬 회원가입 유저 플로우 및 스키마 수정

- src/components/input/LabelContainer.tsx
- src/components/input/TextInput.tsx
- src/pages/EmailVerifyPage/EmailVerifyForm.tsx
- src/pages/LocalSignUpPage/LocalSignUpForm.tsx
- src/presentation/authPresentation.ts
로컬 회원가입 조건을 반영합니다.
중복확인 완료 시 성공 및 실패 문구가 나타나도록 합니다.
비밀번호 클릭 시 조건이 나타날 수 있도록 합니다.
조건은 입력하는대로 변화하도록 합니다.
이때 비밀번호 input에서 focus를 해제하면 조건이 나타나지 않습니다.
비밀번호 확인 input에 한 개 이상의 문자가 들어가면 일치 여부를 확인하는 문구가 하단에 나타납니다.
회원가입하기 버튼을 눌렀을 때 에러는 하단에 나타나도록 합니다.
작성 완료 시 이메일 인증 페이지로 이동합니다.
- 유저 플로우가 맞는지 다시 한 번 확인해주시기 바랍니다.
> ✨ 화면 명세 중 로컬 회원가입 조건 반영

- src/pages/EmailVerifyPage/EmailVerifyForm.tsx
- src/pages/LocalSignUpPage/LocalSignUpForm.tsx
- src/pages/SignInSelectPage/LogInForm.tsx
- src/pages/SignUpSelectPage/index.tsx
- src/presentation/authPresentation.ts
- src/shared/route/useRouteNavigation.ts
- 이메일 인증 페이지에서 전송/재전송 버튼을 분리하였습니다.
- 이전 버튼을 추가하여 로컬 로그인 페이지로 이동하도록 설정하였습니다.
- initialstate 문제로 authPresentation 부분이 변경되었습니다. 근데 삼항연산자가 너무 많기는 해서😂 이게 최선인지는 모르겠습니다..
> ✨ 이메일 인증 페이지 유저 플로우 반영

- src/components/progressBar/ProgressBar.tsx
- src/pages/EmailVerifyPage/EmailVerifyForm.tsx
- src/pages/LocalSignUpPage/LocalSignUpForm.tsx
- progress bar를 생성했습니다.
- 로컬회원가입에만 progress bar가 나타나도록 설정했습니다.
- 로컬 회원가입 시
- 구글 회원가입 시
> ✨ progress bar 로컬 회원가입에만 적용

- src/pages/LandingPage/index.tsx
- src/pages/MyPage/index.tsx
- src/service/authService.ts
- src/shared/api/api.ts
- src/shared/api/client.ts
- src/shared/auth/AuthProtectedRoute.tsx
- 클라우드 프론트에서 모든 헤더를 서버로 전달하도록 설정하였습니다.
- 헤더에 'Authorization: Bearer {token}'의 방식으로 전달되도록 설정하였습니다.
- 로그아웃 시 토큰을 전달하도록 합니다.
> 🚑 인증 토큰이 헤더에 들어가지 않는 문제 해결

- src/pages/EmailVerifyPage/EmailVerifyForm.tsx
> 🐛 코드 전송 시 모달 나타나도록 수정

- .github/workflows/deploy-admin.yml
- .github/workflows/deploy-client.yml
- apps/client/package.json
- package.json
- 태그가 너무 많이 생겨 작업이 더 불편할 거 같아 메인 머지 시 자동 배포되도록 변경
(어차피 두 페이지 모두 서로 거의 유사)
- 추후 1.0.0이 배포되면 그때부터 태그푸시 도입이 필요할 듯
> 💚 태그 푸시 대신 메인에 머지되면 배포되도록 변경

- apps/admin/src/entities/input.ts
- apps/admin/src/feature/post/presentation/companypresentation.ts
- apps/admin/src/feature/post/presentation/postPresentation.ts
- apps/admin/src/feature/post/ui/CreateCompanyForm.tsx
- packages/design-system/src/Button/Button.tsx
- 회사 생성 페이지를 만듭니다.
- presigned url을 사용하여 업로드를 구현해야 합니다.
- 공고 생성 페이지와 연결해야 합니다.
- 다중 string input
- 이미지 업로드 시 썸네일 확인 가능
- pdf 업로드 시 업로드한 파일의 제목 확인 가능
- 다중 객체 input
- 해시태그 입력창 (공백 허용, 공백만 있을 시 태그 생성 불가)
> ✨ 회사 생성 페이지 생성

- apps/client/src/feature/auth/ui/signUp/EmailVerifyForm.tsx
- apps/client/src/pages/EmailVerifyPage.tsx
- 이메일 인증 페이지를 스타일링합니다.
- 초기 페이지는 다음과 같습니다.
- 인증코드를 신청하면 다음과 같은 화면이 나타납니다.
- 인증에 성공하면 다음과 같은 페이지를 확인할 수 있습니다.
- 인증이 만료되면 다음과 같은 페이지를 확인할 수 있습니다.
> 💄 이메일 인증 페이지 스타일링

- apps/client/src/components/field/ImageField.tsx
- apps/client/src/components/field/MarkdownEditorField.tsx
- apps/client/src/components/field/PdfField.tsx
- apps/client/src/components/field/StringField.tsx
- apps/client/src/components/field/StringSelectForm.tsx
- apps/client/src/components/field/StringWithLetterCountField.tsx
- apps/client/src/entities/input.ts
- apps/client/src/entities/post.ts
- apps/client/src/feature/company/presentation/companyFormPresentation.ts
- apps/client/src/feature/company/presentation/companyInputPresentation.ts
- apps/client/src/feature/company/ui/CreateCompanyForm.tsx
- apps/client/src/feature/company/ui/fields/ExternalLinkField.tsx
- apps/client/src/feature/company/ui/fields/HashtagField.tsx
- apps/client/src/feature/company/ui/fields/InvestAmountField.tsx
- apps/client/src/feature/company/ui/fields/InvestCompanyField.tsx
- input과 form의 상태를 presentation 계층에서 함께 관리합니다.
- input state는 입력 가능한 상태 (공백 등 허용), form state는 제출 가능한 상태 (필수 입력 여부에 따른 공백 미허용)를 의미합니다. form state는 input state로부터 가공되며 단독으로 변경이 불가능합니다.
- input presentation 레이어를 form presentation 레이어에 주입하여 사용합니다.
- 필수 입력이 아닌 경우, 아무것도 입력되지 않았다면 에러가 나타나지 않으며 입력 시 에러가 나타나도록 설정하였습니다.
- 다중 input에서 중복된 값 또는 무효값 입력 시 제출하지 않아도 에러를 확인할 수 있도록 설정하였습니다.
- 삭제 시 item을 기준으로 한 filter가 아닌 index를 기준으로 삭제합니다.
> companyPresentation 계층에서 input과 form에 사용하는 상태 함께 관리

- apps/client/src/feature/company/presentation/companyFormPresentation.ts
- apps/client/src/feature/company/ui/CreateCompanyForm.tsx
- apps/client/src/feature/post/service/postService.ts
- apps/client/src/feature/post/ui/PostDetailView.tsx
- apps/client/src/pages/LandingPage.tsx
- packages/api/src/apis/localServer/apis.ts
- 전체 공고 및 상세 공고를 불러올 때 선택적으로 토큰을 사용하도록 설정합니다.
- landingpageLink에 빈 문자열이 들어오면 undefined로 요청을 보냅니다.
> 🐛 공고 불러올 때 토큰 들어가지 않는 문제 해결 및 landingpageLink에 빈 문자열이 들어오면 undefined로 요청 보내기

- eslint.config.js
- src/App.tsx
- src/api/apis/externalServer/apis.ts
- src/api/apis/externalServer/index.ts
- src/api/apis/index.ts
- src/api/apis/localServer/apis.ts
- src/api/apis/localServer/index.ts
- src/api/client.ts
- src/api/index.ts
- 상대경로 import를 허용하지 않는 eslint 룰을 추가하였습니다.
- 현재 상대경로로 들어간 import 들을 모두 상대경로로 수정하였습니다.
> ♻️ 상대경로 import를 허용하지 않는 eslint 룰 추가

- src/feature/coffeeChat/ui/detail/ApplicantCoffeeChatDetailView.tsx
- src/feature/coffeeChat/ui/detail/CompanyCoffeeChatDetailView.tsx
- src/feature/coffeeChat/ui/detail/useCoffeeChatDetailHooks.ts
- src/pages/CompanyCoffeeChatDetailPage.tsx
- 회사 커피챗 상세 페이지 api 연결
- 기존 cancel coffee chat service를 제거하고 update coffeechat status로 거절, 성사, 취소 등 모두 관리하도록 수정함
- 회사, 구직자 detail view에서 공용으로 사용하는 hook을 따로 별도 파일로 뽑아서 정리함 (우선 같은 계층에 hook 파일에 넣어 관리중)
> ✨ 회사 커피챗 상세페이지 api 연결

- src/api/apis/localServer/apis.ts
- src/api/apis/localServer/schemas.ts
- src/entities/coffeeChat.ts
- src/feature/applicant/ui/mypage/ApplicantInfo.tsx
- src/feature/coffeeChat/service/coffeeChatService.ts
- src/feature/coffeeChat/ui/detail/ApplicantCoffeeChatDetailView.tsx
- src/feature/coffeeChat/ui/detail/CompanyCoffeeChatDetailView.tsx
- src/feature/post/ui/detail/PostDetailView.tsx
- src/mocks/applicant/schemas.ts
- src/pages/ApplicantMyPage.tsx
- 커피챗 신청 유무에 따라 커피챗 버튼 활성/비활성화 기능 구현
- 기존 회사 커피챗 상세 페이지에서 유저 정보를 잘못 가져오던 것을 수정
> 커피챗 신청 유무에 따른 커피챗 버튼 활성/비활성화 기능 구현 및 기타 수정

- src/components/ui/badge.tsx
- src/feature/post/ui/common/PostCard.tsx
- src/feature/post/ui/landing/LandingPostView.tsx
- 공고가 너무 길어질 경우 ...으로 줄여줍니다.
- 하단 컴포넌트 위치가 동일하도록 맞춰둡니다.
- 기타 gap, 폰트 크기를 맞추었습니다.
현재 피그마는 1920 기준으로 작성되어 있으며, 카드컴포넌트의 기본 너비가 380px이지만, 현재 홈페이지에선, 너비가 330px로 설정되어 있습니다. 현재 제 노트북도 가로가 1920 픽셀이 안되는 것 같은데, 만약 그렇다면 디자이너님께 카드 컴포넌트 폭을 바꿔달라고 부탁드려야 할 것 같습니다.
- 카드 컴포넌트 수정본
> 💄 카드 컴포넌트 피그마와 동일하게 수정

- src/feature/applicant/presentation/applicantFormPresentation.ts
- src/feature/applicant/ui/mypage/ApplicantProfileInfo.tsx
- src/feature/company/ui/mypage/CompanyProfileInfo.tsx
- 유저 프로필 생성 시 리스트 내부의 빈 문자열을 제거하고 생성하도록 하였습니다.
- 회사 프로필 보기 시 빈 리스트에 대응하도록 설정하였습니다.
> 🐛 프로필 보기 및 생성 시 빈 리스트 및 리스트 내부 빈 문자열 대응

- src/feature/post/ui/detail/PostDetailView.tsx
- src/feature/post/ui/mypage/applicant/BookmarkListView.tsx
- 회사 공고명이 길어진 상황에서의 버그 해결
1.  커피챗 리스트에서 스타일 영역 벗어나는 문제 truncate (...으로 대체)하여 해결
2. 공고 상세 페이지에서 북마크가 찌뿌되는 문제 북마크 figma 스펙에 맞게 사이즈 고정시켜 해결
> 🐛  회사 직군명 길어진 상황 버그 개선

- src/feature/post/presentation/postFormPresentation.ts
- src/feature/post/ui/detail/PostDetailView.tsx
- src/feature/post/ui/form/CreatePostForm.tsx
- 공고 생성 페이지에서 인원에 대한 안내를 추가했습니다
> 🐛  공고 생성 페이지에서 인원에 대한 안내 추가

- src/components/field/MarkdownEditorField.tsx
- 마크다운이 비어있을 때에 다른 인풋을 작성하면 마크다운 에디터로 포커스가 이동하는 버그를 수정하였습니다.
> 🐛 다른 인풋 작성 시에 마크다운 에디터에 포커스 잡히는 버그 픽스

- src/api/apis/localServer/schemas.ts
- src/entities/post.ts
- src/feature/post/ui/common/PostCard.tsx
- 공고 카드에 직군 정보 (어떤 직군을 몇 명이나 뽑는지) 추가합니다.
* Desktop
* Tablet
* Phone
> ✨ 공고 카드에 직군 정보가 추가

- src/feature/post/ui/detail/PostDetailView.tsx
- 모집 인원, 월급 정보를 공고 상세 페이지 하단에서 상단으로 옮겼습니다
- 공고 상세 글은 그대로 하단에 위치합니다
> 💄 모집 인원, 월급 정보 공고 페이지 상단에 표기
