.github/ISSUE_TEMPLATE/bug_issue.yml
.github/ISSUE_TEMPLATE/feature_issue.yml
.github/ISSUE_TEMPLATE/refactor_issue.yml

🎨 리액트 초기 환경 세팅

---

package.json
postcss.config.js
src/App.tsx
src/components/button/button.tsx
src/components/header/NavigationHeader.tsx
src/index.css
src/utils/designSystem.ts
tailwind.config.js
yarn.lock

- tailwind, tw-merge, clsx, cva를 설치하여 테일윈드 css 환경을 생성하였습니다.
- 디자인 시스템이 적용된 버튼 컴포넌트를 생성하였습니다.

➕ 테일윈드 설치 및 환경 설정

---

src/components/button/button.tsx
src/components/header/NavigationHeader.tsx
src/pages/SurveyDetailPage.tsx

💄 상세 페이지 스타일링

---

src/components/header/NavigationHeader.tsx
src/components/header/TitleHeader.tsx
src/components/layout/Layout.tsx
src/pages/SurveyDetailPage.tsx
src/pages/SurveyListPage.tsx
tailwind.config.js

- 모바일 뷰에서 뱃지 너비 깨지는 부분 수정
- 600px 이상일 때 가운데 정렬
- 헤더 그림자는 최대한 아래만을 향하도록 수정

💄 반응형에서 깨지는 부분 수정

---

.github/ISSUE_TEMPLATE/refactor_issue.yml
.github/workflows/deploy_dev.yml
.github/workflows/deploy_prod.yml

🚀 개발 및 배포 버전 CI 생성

---

.github/workflows/deploy_dev.yml
.github/workflows/deploy_prod.yml

💚 배포 아이디 변경

---

src/App.tsx

✨ 에코 서버를 위한 페이지 생성

---

src/components/form/FormContainer.tsx
src/components/form/index.tsx
src/components/input/LabelContainer.tsx
src/components/input/TextInput.tsx
src/components/input/index.tsx
src/pages/EmailVerifyPage/index.tsx
src/pages/LandingPage/LogInForm.tsx
src/pages/SignUpPage/LocalSignUpForm.tsx

- Form: 각각의 input을 children으로 받습니다. 이때 form에 필수적으로 들어가는 버튼과 서버로부터 받은 에러 응답을 표현합니다.
- input: text input을 받을 수 있는 컴포넌트를 생성합니다.
- LabelContainer: 라벨 및 각 input에 대한 description을 관리합니다.

✨Form과 Input을 관리하기 위한 공통 컴포넌트 생성

---

.github/workflows/deploy_dev.yml
.github/workflows/deploy_prod.yml

- 깃허브 액션 secret으로 구글 클라이언트 ID를 배포시에도 관리합니다.

🚑 gitignore된 .env 정보 추가

---

.github/workflows/deploy_dev.yml
.github/workflows/deploy_prod.yml

🚑 CI 세팅에서 secret 이름 수정

---

src/App.tsx
src/entities/route.ts
src/pages/EmailVerifyPage/EmailVerifyForm.tsx
src/pages/SignUpCompletePage/index.tsx
src/shared/route/useRouteNavigation.ts

- 회원 가입 완료 페이지를 생성합니다.
- 이메일 인증 완료 시 바로 메인이 아닌 회원 가입 완료 페이지를 거치도록 합니다.

✨ 회원가입 완료 페이지 생성

---

src/pages/EmailVerifyPage/EmailVerifyForm.tsx
src/pages/LocalSignUpPage/LocalSignUpForm.tsx

- 유효한 input이 들어왔을 때만 버튼이 활성화되도록 설정합니다.

✨ 회원가입 시 버튼 disable 설정

---

src/shared/api/api.ts

🚑 마이페이지 url 변경

---

src/components/input/TextInput.tsx
src/pages/EmailVerifyPage/EmailVerifyForm.tsx
src/pages/LocalSignUpPage/LocalSignUpForm.tsx
src/presentation/authPresentation.ts

🐛 이메일 input에서 @snu.ac.kr 제거

---

src/components/input/TextInput.tsx
src/pages/EmailVerifyPage/EmailVerifyForm.tsx
src/pages/LocalSignUpPage/LocalSignUpForm.tsx
src/pages/SignUpSelectPage/GoogleSocialSignUpButton.tsx
src/presentation/authPresentation.ts
src/service/authService.ts
src/shared/api/api.ts
src/shared/api/entities/schemas.ts

✨ 스누메일 구글 계정 사용 시 즉시 회원가입

---

src/pages/SignUpSelectPage/GoogleSocialSignUpButton.tsx

- 불필요한 state 정리
- implicit 방식 대신 auth-code 방식으로 변경 (보안상 더 권장됨.)
https://developers.google.com/identity/oauth2/web/guides/choose-authorization-model?hl=ko

🐛 implicit 대신 auth code 방식으로 변경

---

src/entities/route.ts
src/mocks/post/data.ts
src/mocks/post/handlers.ts
src/mocks/post/resolvers.ts
src/mocks/post/schemas.ts
src/pages/LandingPage/PostPage/index.tsx
src/pages/LandingPage/index.tsx

- /post, /post/:postId 에 대응하는 mock api를 작성했습니다.
- 관련해서 테스트 없이 작성했던 로직의 문제점을 고쳤어요. 

[FEAT] post, postid mock api 작성

---

src/pages/SignUpSelectPage/GoogleSocialSignUpButton.tsx

- flow: auth-code에서 제공하는 code가 access token이 아니었습니다.. 다시 access token으로 변경했습니다.

🚑 잘못된 access token이 전달되는 현상 수정

---

src/entities/response.ts
src/mocks/auth/resolvers.ts
src/mocks/auth/schemas.ts
src/pages/EmailVerifyPage/AddSignUpModal.tsx
src/pages/EmailVerifyPage/EmailVerifyForm.tsx
src/pages/SignUpSelectPage/GoogleSocialSignUpButton.tsx
src/service/authService.ts
src/service/echoService.ts
src/service/postService.ts
src/service/userService.ts
src/shared/api/api.ts
src/shared/api/entities/params.ts

- 로컬 / 소셜 통합 회원가입을 지원합니다.
- 이미 동일한 스누메일로 가입한 이력이 있을 경우 모달창을 띄워 다른 회원가입을 진행할지 물어보는 모달을 띄웁니다.
- 모달에서 확인 버튼을 누를 시 새로운 회원가입 방식을 지원합니다.
- 동일한 회원가입 방식을 시도할 경우에는 회원가입을 진행할 수 없습니다.

✨ 통합 회원가입 기능 생성

---

src/pages/LandingPage/index.tsx
src/service/postService.ts
src/shared/api/api.ts
src/shared/api/client.ts
src/shared/api/entities/schemas.ts

api/client.ts 에 있는 callWithoutToken이 token?: string이고, api/api.ts 내에서 정의된 타입의 callWithoutToken은 token?: never로 타입을 좁히길래 이름만 바꿔서 재탕해봤습니다.

CallWithOptionalToken 생성

---

src/mocks/post/data.ts
src/mocks/post/resolvers.ts
src/mocks/post/schemas.ts
src/pages/LandingPage/index.tsx
src/shared/api/entities/schemas.ts

- 정상적으로 response에 대응되도록 코드를 수정했습니다.

[FIX] /post 에 대한 response type 지정이 잘못된 코드 수정

---

src/service/postService.ts
src/shared/api/api.ts
src/shared/api/entities/schemas.ts

- 삭제 로직은 안 만들고, 우선 생성, 수정 로직만 마무리했습니다.

[FEAT] Post 생성, 수정 api 로직 작성하기

---

src/entities/post.ts
src/pages/LandingPage/FilterModal.tsx
src/pages/LandingPage/index.tsx
src/service/postService.ts
src/shared/api/entities/schemas.ts

[FEAT] 필터링 기능 구현 완료하기

---

src/pages/LandingPage/FilterModal.tsx
src/pages/LandingPage/PostCard.tsx
src/pages/LandingPage/PostPage/index.tsx
src/pages/LandingPage/index.tsx
src/service/postService.ts
src/shared/api/entities/schemas.ts

- 랜딩페이지에 회사 목록을 카드 컴포넌트로 보여줍니다.

[STYLE] 카드 컴포넌트 추가

---

src/entities/post.ts
src/pages/LandingPage/FilterModal.tsx
src/pages/LandingPage/index.tsx

- type은 entity 폴더로 옮겼습니다.
- filter 기능에 쓰이는 state를 묶어서 FilterModal에 전달합니다.

[REFACTOROR] 랜딩페이지와 필터링 기능들의 코드르 정리

---

src/entities/post.ts
src/pages/LandingPage/FilterModal.tsx
src/pages/LandingPage/PostPage/index.tsx
src/pages/LandingPage/index.tsx

- 포스트 자세히 보기 페이지를 눈에 보이게 레이아웃만 작성했습니다.
- filter에서 investor를 제외했습니다.

STYLE & FEATUER post detail page를 AI에게 맡기고, filter에서 investor 제외

---

src/pages/LandingPage/PostCard.tsx
src/pages/LocalSignUpPage/LocalSignUpForm.tsx
src/shared/api/entities/schemas.ts

- 이름 무효 시 하단에 경고 메세지 나타나도록 설정
- 마감일 invalid Date로 나오는 문제 해결 (schema 및 시간 포매팅)

✨ 이름 무효 시 하단에 경고 메세지 나타나도록 설정

---

src/pages/LandingPage/PostCard.tsx
src/pages/LandingPage/PostPage/index.tsx
src/shared/api/entities/schemas.ts

- isActive 대신 마감일과 현재 시각을 비교합니다. (더미 데이터 이슈)

🐛 마감일 버그 수정

---

src/pages/EmailVerifyPage/EmailVerifyForm.tsx

- 이메일 인증 시 conflict 발생 이후 모달 띄우기

🐛 이메일 인증 시 conflict 발생 이후 모달 띄우기

---

src/pages/LandingPage/PostCard.tsx
src/pages/LandingPage/PostPage/index.tsx
src/shared/api/entities/schemas.ts

- post 스키마 중 employeeEndDate를 employmentEndDate로 변경하였습니다.
- isActive를 사용하여 종료 여부를 확인합니다.

🐛 post 스키마 중 employeeEndDate를 employmentEndDate로 변경

---

.github/workflows/deploy-admin.yml
.github/workflows/deploy-client.yml

- admin과 client 태그를 기반으로 배포를 자동화합니다.

👷 분리 배포를 위한 CI 생성

---

.github/workflows/deploy-admin.yml
.github/workflows/deploy-client.yml

🚑 CI 변경되지 않는 부분 수정

---

.pnp.cjs
apps/admin/tailwind.config.js
packages/design-system/eslint.config.js
packages/design-system/package.json
packages/design-system/src/Button/Button.tsx
packages/design-system/src/utils/merge.ts
yarn.lock

- variant를 적용할 수 있도록 cva를 세팅합니다.

✨디자인시스템 패키지에 cva 적용

---

apps/admin/src/App.tsx
apps/admin/src/entities/input.ts
apps/admin/src/entities/route.ts
apps/admin/src/feature/auth/presentation/authPresentation.ts
apps/admin/src/feature/post/index.tsx
apps/admin/src/feature/post/presentation/postPresentation.ts
apps/admin/src/feature/post/ui/CreateCompanyForm.tsx
apps/admin/src/feature/post/ui/CreatePostForm.tsx
apps/admin/src/pages/CreateCompanyPage.tsx
apps/admin/src/pages/CreatePostPage.tsx
apps/admin/src/shared/route/useRouteNavigation.ts

- post 생성에 필요한 state 관리를 위해 presentation 계층을 생성합니다.
- 각 input은 아직 customizing 하지 않았으며, 기본 input type을 사용합니다.

✨ post 생성 스켈레톤 코드 작성

---

.pnp.cjs
apps/client/src/pages/LandingPage/Pagination.tsx
apps/client/src/pages/LandingPage/PostCard.tsx
apps/client/src/pages/LandingPage/index.tsx

- yarn install 실행 시 pnp.cjs가 변경되어 해당 내용을 반영합니다.
- map 사용시 key를 중복되지 않도록 설정합니다.

🐛 yarn install 실행 시 pnp.cjs 변경 사항 반영

---

.pnp.cjs
apps/client/package.json
apps/client/src/App.tsx
apps/client/src/entities/decodedToken.ts
apps/client/src/shared/auth/CompanyProtectedRoute.tsx
apps/client/src/shared/route/RouteNavigator.tsx
packages/design-system/package.json
yarn.lock

- 회사 권한이 없는 사람은 회사 페이지를 들어갈 수 없도록 설정합니다.

✨ 회사 권한이 없는 사람은 회사 페이지를 들어갈 수 없도록 설정

---

apps/client/src/App.tsx
apps/client/src/entities/input.ts
apps/client/src/feature/post/presentation/companypresentation.ts
apps/client/src/feature/post/presentation/postPresentation.ts
apps/client/src/feature/post/ui/CreateCompanyForm.tsx
apps/client/src/feature/post/ui/CreatePostForm.tsx

- 다중 input에서 중복되는 input이 발생하지 않도록 방지합니다.
- 다중 input에서 엔터를 입력 시 새로운 input이 나타나도록 설정하여 사용자 경험을 향상하였습니다.
- 해시태그 입력 시 중복되는 태그를 다시 입력하면 태그 생성이 불가능하도록 방어합니다.
- 파일 업로드 시 사진 1MB, pdf 5MB 이상을 업로드하지 않도록 하였으며, 이외의 확장자를 허용하지 않습니다.

✨ 채용 공고 및 회사 정보 작성 시 엣지 케이스 방어

---

apps/client/src/entities/post.ts
apps/client/src/feature/post/presentation/companypresentation.ts
apps/client/src/feature/post/presentation/postPresentation.ts
apps/client/src/feature/post/service/postService.ts
apps/client/src/feature/post/ui/CreateCompanyForm.tsx
apps/client/src/feature/post/ui/CreatePostForm.tsx
apps/client/src/pages/LandingPage/FilterSection.tsx
apps/client/src/shared/route/useRouteNavigation.ts
packages/api/src/apis/localServer/schemas.ts

- 외부 서버 (AWS S3등)와 연결될 수 있도록 api 설정을 변경하였습니다.
- post 생성 전 S3에 이미지와 파일을 업로드할 수 있도록 설정하였습니다.
- post 생성 api가 아직 완성되지 않아 일단 프론트에서만 달아두었습니다.

✨ post 생성 api와 연결

---

.pnp.cjs
apps/client/package.json
apps/client/src/feature/post/presentation/postPresentation.ts
apps/client/src/feature/post/ui/CreateCompanyForm.tsx
apps/client/src/feature/post/ui/CreatePostForm.tsx
yarn.lock

✨ 마크다운 에디터 적용

---

apps/client/src/App.tsx
apps/client/src/feature/ventureCapital/index.tsx
apps/client/src/feature/ventureCapital/ui/MyCompanyList.tsx
apps/client/src/feature/ventureCapital/ui/MyPage.tsx
apps/client/src/feature/ventureCapital/ui/MyPostList.tsx
apps/client/src/feature/ventureCapital/ui/VentureCapitalLandingTab.tsx
apps/client/src/pages/VentureCapitalLandingPage.tsx
apps/client/src/shared/auth/AuthAdminSwitchRoute.tsx

- VC 로그인 시 VC 전용 랜딩 페이지가 나타나도록 수정

✨ vc 로그인 시 vc 전용 랜딩 페이지가 나타나도록 수정

---

.pnp.cjs
apps/client/components.json
apps/client/index.html
apps/client/package.json
apps/client/src/components/form/FormContainer.tsx
apps/client/src/components/ui/button.tsx
apps/client/src/components/ui/input.tsx
apps/client/src/components/ui/label.tsx
apps/client/src/components/ui/layout.tsx
apps/client/src/feature/auth/ui/signIn/GoogleSocialSignInButton.tsx
apps/client/src/feature/auth/ui/signIn/LocalLoginForm.tsx
apps/client/src/index.css
apps/client/src/lib/utils.ts
apps/client/src/pages/SignInSelectPage.tsx
apps/client/tailwind.config.js
yarn.lock

- 로그인 페이지 스타일링을 완료하였습니다.
- shadcn을 사용하여 스타일링하였습니다.
- 진입 화면
- 입력 시 버튼이 변경됩니다.
- 글자 호버 시 underline이 생성됩니다.

💄 로그인 페이지 스타일링

---

apps/client/src/entities/post.ts
apps/client/src/feature/landing/hooks/useGetPosts.ts
apps/client/src/feature/landing/ui/FilterSection.tsx
apps/client/src/feature/landing/ui/PostCard.tsx
apps/client/src/feature/post/service/postService.ts
apps/client/src/pages/LandingPage.tsx

post api에 Series 반영

---

apps/client/src/components/form/FormContainer.tsx
apps/client/src/entities/author.ts
apps/client/src/entities/errors.ts
apps/client/src/entities/post.ts
apps/client/src/entities/response.ts
apps/client/src/entities/resume.ts
apps/client/src/entities/user.ts
apps/client/src/feature/auth/service/authService.ts
apps/client/src/feature/auth/ui/signIn/GoogleSocialSignInButton.tsx
apps/client/src/feature/auth/ui/signIn/LocalLoginForm.tsx
apps/client/src/feature/auth/ui/signUp/EmailVerifyForm.tsx
apps/client/src/feature/auth/ui/signUp/GoogleSocialSignUpButton.tsx
apps/client/src/feature/post/service/postService.ts
apps/client/src/feature/resume/service/resumeService.ts
apps/client/src/feature/resume/ui/ResumeList.tsx
apps/client/src/feature/user/service/userService.ts
apps/client/src/feature/user/ui/MyInfo.tsx
apps/client/src/shared/file/fileService.ts
packages/api/src/apis/localServer/schemas.ts
packages/api/src/entities/index.ts

✨ 로그인 및 회원가입 DTO 변경사항 수정

---

apps/client/src/components/form/FormContainer.tsx
apps/client/src/components/progressBar/ProgressBar.tsx
apps/client/src/components/ui/layout.tsx
apps/client/src/feature/auth/ui/signUp/AddSignUpModal.tsx
apps/client/src/feature/auth/ui/signUp/EmailVerifyForm.tsx
apps/client/src/pages/LocalSignUpPage.tsx
apps/client/src/pages/SignUpCompletePage.tsx

- 회원가입 완료 페이지를 스타일링하였습니다.
- 회원가입 병합 완료 및 이미 회원가입 되었음을 알리는 모달을 스타일링하였습니다.

💄 회원가입 완료 페이지 및 모달 스타일링

---

apps/client/src/feature/auth/ui/signUp/EmailVerifyForm.tsx
packages/api/src/apis/localServer/schemas.ts

- 회원가입 시 conflict에 따라 모달이 정상적으로 나타나도록 수정하였습니다.

🐛 회원가입 시 conflict에 따라 모달이 정상적으로 나타나도록 수정

---

apps/client/src/feature/auth/ui/signUp/EmailVerifyForm.tsx
apps/client/src/feature/auth/ui/signUp/GoogleSocialSignUpButton.tsx
packages/api/src/apis/localServer/schemas.ts

- 회원가입 conflict 종류에 따라 모달 타입이 달라지도록 설정하였습니다.

🐛 회원가입 시 모달 정상적으로 나타나도록 수정

---

apps/client/src/entities/errors.ts
apps/client/src/feature/auth/ui/signIn/GoogleSocialSignInButton.tsx
apps/client/src/feature/auth/ui/signIn/LocalLoginForm.tsx
apps/client/src/feature/auth/ui/signUp/EmailVerifyForm.tsx
apps/client/src/feature/auth/ui/signUp/GoogleSocialSignUpButton.tsx
apps/client/src/feature/auth/ui/signUp/LocalSignUpForm.tsx
apps/client/src/feature/company/ui/CreateCompanyForm.tsx
apps/client/src/feature/post/ui/CreatePostForm.tsx

- setResponseMessage에서 상세 에러 코드 대신 에러 메세지를 넣도록 수정하였습니다.

♻️ setResponseMessage에서 에러 코드 대신 에러 메세지를 넣도록 수정

---

apps/client/src/App.tsx
apps/client/src/entities/filter.ts
apps/client/src/feature/auth/service/authService.ts
apps/client/src/feature/landing/hooks/useGetPosts.ts
apps/client/src/feature/landing/service/landingService.ts
apps/client/src/feature/landing/ui/FilterSection.tsx
apps/client/src/feature/landing/ui/PostCard.tsx
apps/client/src/feature/landing/ui/RolesFilter.tsx
apps/client/src/feature/post/service/postService.ts
apps/client/src/pages/LandingPage.tsx
apps/client/src/shared/context/RolesFilterContext.tsx
apps/client/src/shared/context/ServiceContext.ts
apps/client/src/shared/rolesFilter/localstorage.ts
apps/client/src/shared/rolesFilter/state.ts

- state와 localstorage를 관리하는 로직은 repository로 추상화하여 service 레이어의 파라미터로 주입하였습니다.
- 불필요한 메서드를 삭제하였습니다.

♻️ roles filter가 service-repository 구조를 갖추도록 리팩토링

---

apps/client/src/components/modal/ReSignInModal.tsx
apps/client/src/components/nav/GlobarNavigationBar.tsx
apps/client/src/components/ui/button.tsx
apps/client/src/components/ui/layout.tsx
apps/client/src/feature/landing/ui/PostCard.tsx
apps/client/src/pages/CreateCompanyPage.tsx
apps/client/src/pages/CreatePostPage.tsx
apps/client/src/pages/CreateResumePage.tsx
apps/client/src/pages/EmailVerifyPage.tsx
apps/client/src/pages/LandingPage.tsx
apps/client/src/pages/LocalSignUpPage.tsx
apps/client/src/pages/MyPage.tsx
apps/client/src/pages/PostDetailPage.tsx
apps/client/src/pages/ResumeDetailPage.tsx
apps/client/src/pages/ResumeListPage.tsx
apps/client/src/pages/SignInSelectPage.tsx
apps/client/src/pages/SignUpCompletePage.tsx
apps/client/src/pages/SignUpSelectPage.tsx
apps/client/src/pages/VentureCapitalLandingPage.tsx
apps/client/src/shared/route/useRouteNavigation.ts
apps/client/tailwind.config.js

- 글로벌 네비게이션 바를 생성하였습니다.
- 반응형 스타일링을 적용하였습니다.
- GNB가 필요한 페이지에 모두 gnb를 적용하였습니다.

✨ 글로벌 네비게이션 바 적용

---

apps/client/src/components/button/Button.tsx
apps/client/src/components/nav/GlobarNavigationBar.tsx
apps/client/src/entities/resume.ts
apps/client/src/feature/resume/presentation/resumePresentation.ts
apps/client/src/feature/resume/service/resumeService.ts
apps/client/src/feature/resume/ui/CreateResumeForm.tsx
apps/client/src/feature/resume/ui/ResumeList.tsx
apps/client/src/pages/CreateResumePage.tsx

커피챗 신청하기 및 커피챗 리스트 로직을 만들었습니다.

[FEAT] 커피챗 신청하기 및 리스트 로직 작성과 서버 연결 확인 (마침내!)

---

apps/client/src/components/nav/GlobarNavigationBar.tsx
apps/client/src/pages/LandingPage.tsx
apps/client/tailwind.config.js

- 페이지 breakpoint를 피그마와 동일하게 픽셀 조정
- 최대 페이지의 경우, 피그마에 따로 나와있는 컨텐츠 크기가 존재하지 않아 1500px로 설정

💄 페이지 breakpoint 피그마와 동일하게 픽셀 조정

---

apps/client/src/feature/user/service/userService.ts
packages/api/src/apis/localServer/apis.ts

user/info -> user/me 로 엔드포인트 변경했습니다.
마이페이지에서 정상적으로 데이터 출력 되는 점 확인했습니다.

[FEAT] 마이페이지 api 서버 연결 확인

---

apps/client/package.json
apps/client/src/components/ui/button.tsx
apps/client/src/components/ui/popover.tsx
apps/client/src/components/ui/radio-group.tsx
apps/client/src/entities/post.ts
apps/client/src/feature/landing/hooks/useGetPosts.ts
apps/client/src/feature/landing/ui/FilterSection.tsx
apps/client/src/feature/post/service/postService.ts
yarn.lock

- 모집 중 라디오 버튼 모달을 생성했습니다
- 시리즈 테크박스 버튼 모달을 생성하였습니다. 전체 선택이 가능합니다.
- 적용 버튼을 눌렀을 때 필터링이 적용되며, 모집 중 모달에서는 선택한 옵션이 나타나도록 설정했습니다.
- 초기화 클릭시 선택한 옵션을 모두 초기화할 수 있습니다.

✨ 모집 중 및 시리즈 필터 모달 생성

---

apps/client/src/feature/landing/ui/PostCard.tsx

- 회사 대표 이미지가 존재하지 않는다면 회색 박스가 나타나도록 설정합니다.

🐛 이미지가 존재하지 않는 경우 대응

---

apps/client/src/components/nav/GlobarNavigationBar.tsx
apps/client/src/components/ui/badge.tsx
apps/client/src/feature/landing/ui/PostCard.tsx
apps/client/src/pages/LandingPage.tsx

💄카드 컴포넌트 패딩 및 뱃지 위치 조정

---

apps/client/src/components/modal/CancelCheckModal.tsx
apps/client/src/components/modal/RewritePostModal.tsx
apps/client/src/components/ui/button.tsx
apps/client/src/entities/route.ts
apps/client/src/feature/post/ui/CreatePostForm.tsx
apps/client/src/feature/resume/presentation/resumePresentation.ts
apps/client/src/feature/resume/ui/CreateResumeForm.tsx
apps/client/src/pages/CreateCompanyPage.tsx
apps/client/src/pages/CreatePostPage.tsx
apps/client/src/shared/auth/CompanyProtectedRoute.tsx
apps/client/src/shared/route/useRouteNavigation.ts

- 공고 작성 완료 시 공고 재작성 모달이 나타나도록 설정하였습니다. (임시)
- 다중 input을 사용하여 여러 공고를 한번에 처리합니다.

✨ 공고 재작성 모달 추가

---

apps/client/src/components/card/dDayCard.tsx
apps/client/src/feature/landing/ui/PostCard.tsx
apps/client/src/feature/post/service/postService.ts
apps/client/src/feature/post/ui/BookmarkListView.tsx
apps/client/src/feature/post/ui/PostDetailView.tsx
apps/client/src/feature/resume/ui/ResumeDetailView.tsx
apps/client/src/feature/resume/ui/ResumeList.tsx
apps/client/src/pages/MyPage.tsx
apps/client/src/pages/ResumeDetailPage.tsx
apps/client/src/util/format.ts
apps/client/src/util/postFormatFunctions.ts
packages/api/src/apis/localServer/apis.ts
packages/api/src/apis/localServer/schemas.ts

관심공고와 더불어 커피챗 디테일 스타일링, 마이페이지 스타일링을 했습니다.
날짜를 format하는 함수들을 모아서 따로 빼놨습니다.

get 관심 공고 기능 만들고 스타일링

---

apps/client/src/feature/company/ui/CreateCompanyForm.tsx
apps/client/src/feature/post/ui/CreatePostForm.tsx
apps/client/src/pages/CreatePostPage.tsx

- 공고 생성 페이지에 공통 필드 컴포넌트를 적용하였습니다.
- 공고 생성 페이지만의 필드는 스타일링 이후 feature/ui/field에 적용합니다.

♻️ 공고 생성 페이지에 공통 필드 컴포넌트 적용

---

apps/client/src/components/form/FormContainer.tsx
apps/client/src/feature/auth/ui/signIn/LocalLoginForm.tsx
apps/client/src/feature/auth/ui/signUp/EmailVerifyForm.tsx
apps/client/src/feature/auth/ui/signUp/LocalSignUpForm.tsx
apps/client/src/feature/company/ui/CreateCompanyForm.tsx
apps/client/src/feature/post/presentation/postFormPresentation.ts
apps/client/src/feature/post/presentation/postInputPresentation.ts
apps/client/src/feature/post/ui/CreatePostForm.tsx
apps/client/src/feature/resume/ui/CreateResumeForm.tsx
packages/eslint-react/package.json
yarn.lock

- 공고 생성 시 input과 form state로 유효성을 판별합니다.

✨ 공고 생성 시 input 및 form state로 관리

---

apps/client/src/entities/post.ts
apps/client/src/feature/company/presentation/companyFormPresentation.ts
apps/client/src/feature/company/ui/CreateCompanyForm.tsx
apps/client/src/feature/post/service/postService.ts
apps/client/src/feature/post/ui/CreatePostForm.tsx
apps/client/src/feature/post/ui/PostDetailView.tsx
apps/client/src/shared/auth/AuthAdminSwitchRoute.tsx
packages/api/src/apis/localServer/apis.ts
packages/api/src/apis/localServer/schemas.ts

👽️ 회사 생성 API 변경사항 반영

---

apps/client/src/entities/post.ts
apps/client/src/feature/post/presentation/postFormPresentation.ts
apps/client/src/feature/post/presentation/postInputPresentation.ts
apps/client/src/feature/post/service/postService.ts
apps/client/src/feature/post/ui/CreatePostForm.tsx
packages/api/src/apis/localServer/apis.ts
packages/api/src/apis/localServer/schemas.ts

👽️ 공고 생성 API 변경사항 반영

---

apps/client/src/feature/company/ui/CreateCompanyForm.tsx
apps/client/src/feature/company/ui/fields/SloganField.tsx
apps/client/src/feature/post/ui/CreatePostForm.tsx
apps/client/src/feature/post/ui/field/JobCategoryField.tsx

- 슬로건 input 줄이 늘어날 때마다 textarea height가 증가하도록 설정

💄 슬로건 input 줄이 늘어날 때마다 textarea height가 증가하도록 설정

---

apps/client/src/components/button/CancelButton.tsx
apps/client/src/components/field/ImageField.tsx
apps/client/src/feature/company/presentation/companyInputPresentation.ts
apps/client/src/feature/company/ui/fields/HashtagField.tsx

💄 해시태그 input 스타일링

---

apps/client/src/feature/company/ui/CreateCompanyForm.tsx
apps/client/src/feature/company/ui/fields/ExternalLinkField.tsx
apps/client/src/feature/post/ui/PostDetailView.tsx

💄 외부 소개 링크 스타일링

---

apps/client/src/components/field/ImageField.tsx
apps/client/src/components/field/PdfField.tsx
apps/client/src/feature/company/presentation/companyFormPresentation.ts
apps/client/src/feature/company/presentation/companyInputPresentation.ts
apps/client/src/feature/company/ui/CreateCompanyForm.tsx

- state 대신 async mutation을 사용하여 presigned url을 관리합니다.
- 5개의 API 요청 중 하나라도 오류가 발생한다면 메인으로 이동하지 않습니다.

🚑 이미지 링크가 요청에 반영되지 않는 오류 해결

---

apps/client/.env.dev
apps/client/.env.prod
apps/client/src/App.tsx
apps/client/src/components/field/StringSelectField.tsx
apps/client/src/entities/post.ts
apps/client/src/feature/company/ui/CreateCompanyForm.tsx
apps/client/src/feature/landing/ui/PostCard.tsx
apps/client/src/feature/post/ui/PostDetailView.tsx
apps/client/src/shared/file/fileService.ts
packages/api/src/apis/externalServer/schemas.ts
packages/api/src/apis/localServer/schemas.ts
packages/api/src/client.ts
packages/api/src/entities/index.ts

🐛 랜딩페이지 및 상세 페이지에 이미지 띄우기

---

apps/client/src/feature/company/ui/CreateCompanyForm.tsx

🚑 assets 대신 static 사용

---

apps/client/src/shared/auth/CompanyProtectedRoute.tsx

- 회사 protected guard에서 curator 변경 사항을 적용합니다.

🚑 회사 protected guard 내용 수정

---

apps/client/src/entities/post.ts
apps/client/src/feature/landing/index.tsx
apps/client/src/feature/landing/ui/PostCard.tsx
apps/client/src/feature/post/ui/BookmarkListView.tsx
apps/client/src/feature/post/ui/CreatePostForm.tsx
apps/client/src/feature/post/ui/PostDetailView.tsx
apps/client/src/feature/ventureCapital/service/ventureCapitalService.ts
apps/client/src/feature/ventureCapital/ui/MyCompanyList.tsx
apps/client/src/feature/ventureCapital/ui/MyPostList.tsx
apps/client/src/feature/ventureCapital/ui/PostCard.tsx
apps/client/src/feature/ventureCapital/ui/VentureCapitalLandingTab.tsx
packages/api/src/apis/localServer/apis.ts
packages/api/src/apis/localServer/schemas.ts
packages/api/src/entities/index.ts

✨ 내가 작성한 채용 공고 띄우기

---

apps/client/src/feature/post/ui/BookmarkListView.tsx
apps/client/src/feature/resume/ui/ResumeList.tsx
apps/client/src/feature/user/ui/MyInfo.tsx
apps/client/src/feature/ventureCapital/ui/MyPage.tsx
apps/client/src/pages/MyPage.tsx

- VC 및 일반 유저 마이 페이지 스타일링
- 스켈레톤 로딩 추가

💄 VC 및 일반 유저 마이 페이지 스타일링

---

apps/client/src/components/field/PdfField.tsx
apps/client/src/components/field/StringSelectField.tsx
apps/client/src/feature/company/presentation/companyFormPresentation.ts
apps/client/src/feature/company/ui/CreateCompanyForm.tsx
apps/client/src/feature/post/presentation/postFormPresentation.ts
apps/client/src/feature/post/ui/CreatePostForm.tsx
apps/client/src/feature/post/ui/field/EmploymentEndDateField.tsx
apps/client/src/feature/post/ui/field/JobCategoryField.tsx
apps/client/src/feature/user/ui/MyInfo.tsx
apps/client/src/pages/CreateCompanyPage.tsx

- 회사 공고 페이지 너비를 넓혔습니다.
- 회사 생성 시 pdf 에러가 나타나면 잘못 올라온 pdf를 보이지 않도록 설정합니다.
- 공고 생성 시 선택 폼 설정 시 모달이 닫히도록 설정합니다.
- 공고 생성 시 채용 마감일이 오늘 이전인 경우 에러가 발생하도록 처리합니다.

🐛회사 및 공고 생성 에러 수정

---

apps/client/src/components/nav/GlobarNavigationBar.tsx
apps/client/src/feature/user/ui/MyInfo.tsx

- 토큰 가드가 있는 페이지에서 로그아웃 시 재로그인 요청 뜨는 오류를 수정하였습니다.
- 로그아웃 이후에는 랜딩페이지로 이동하도록 설정합니다.

🐛 토큰 가드가 있는 페이지에서 로그아웃 시 재로그인 요청 뜨는 오류 수정

---

apps/client/src/App.tsx
apps/client/src/feature/landing/ui/PostCard.tsx
apps/client/src/feature/post/ui/PostDetailView.tsx
apps/client/src/feature/ventureCapital/index.tsx
apps/client/src/feature/ventureCapital/ui/VentureCapitalMyTab.tsx
apps/client/src/pages/VentureCapitalMyPage.tsx
apps/client/src/shared/auth/AuthAdminSwitchRoute.tsx
apps/client/src/shared/auth/CompanyProtectedRoute.tsx
apps/client/src/shared/context/TokenContext.ts
apps/client/src/shared/token/localstorage.ts
apps/client/src/shared/token/state.ts

- 토큰 내부의 role 데이터를 기반으로 페이지 접근 권한을 확인합니다.
- role은 전역 변수로 관리됩니다.
- vc 회원은 커피챗 신청 및 북마크 버튼을 확인할 수 없습니다.

✨ 페이지 인증 및 인가 적용

---

apps/client/src/components/modal/SignInForCoffeChatModal.tsx
apps/client/src/feature/post/ui/PostDetailView.tsx

- 비로그인 상태에서 커피챗 신청 버튼을 누르면 로그인 유도 모달이 나타나도록 설정합니다.

✨ 비로그인 상태에서 커피챗 신청 버튼을 누르면 로그인 유도 모달 나타나도록 설정

---

apps/client/src/feature/resume/ui/ResumeDetailView.tsx
apps/client/src/feature/resume/ui/SkeletonResumeDetailView.tsx

커피챗 상세 페이지 로딩 중 skeleton UI를 띄우도록 만들었습니다.

커피챗 상세 페이지 skeleton UI 작성

---

apps/client/src/feature/company/ui/CreateCompanyForm.tsx
apps/client/src/feature/post/ui/CreatePostForm.tsx

🐛 다중 다운로드 이슈 해결

---

apps/client/src/feature/post/ui/PostDetailView.tsx

- IR 덱 링크에서 다운로드 가능하도록 설정하였습니다.
- 새로운 창에서 PDF를 확인하며 다운로드 또한 가능합니다.

🐛 IR 덱 링크에서 다운로드 되지 않는 문제 수정

---

apps/client/src/feature/landing/ui/FilterSection.tsx

🐛 필터 중 시리즈 A 추가

---

apps/client/src/components/modal/SignUpModal.tsx
apps/client/src/feature/auth/ui/signIn/GoogleSocialSignInButton.tsx
apps/client/src/feature/auth/ui/signIn/LocalLoginForm.tsx
apps/client/src/pages/SignInSelectPage.tsx

- 아이디와 비밀번호가 틀렸을 경우 '아이디 또는 비밀번호가 일치하지 않습니다.'를 띄웁니다.
- 회원가입하지 않은 유저일 경우 회원가입 유도 모달을 띄웁니다.

🐛 회원가입 하지 않은 유저에 대해 회원가입 유도 모달 띄우기

---

apps/client/src/feature/landing/ui/FilterSection.tsx

- 초기화 버튼 클릭 시 선택된 옵션들도 함께 초기화됩니다.

🐛 초기화 버튼 클릭 시 선택된 옵션들도 함께 초기화

---

apps/client/src/feature/company/presentation/companyFormPresentation.ts
apps/client/src/feature/company/ui/CreateCompanyForm.tsx

🐛 투자 금액 상한선 설정

---

apps/client/src/components/modal/RewritePostModal.tsx
apps/client/src/entities/post.ts
apps/client/src/feature/company/ui/CreateCompanyForm.tsx
apps/client/src/feature/post/service/postService.ts
apps/client/src/feature/post/ui/CreatePostForm.tsx
packages/api/src/apis/localServer/apis.ts
packages/api/src/apis/localServer/schemas.ts

- 회사 생성 이후에는 마이 페이지로 이동합니다.
- 공고 생성 이후에는 공고 상세 페이지로 이동합니다.

✨ 회사 및 공고 생성 시 리다이렉트 포인트 재설정

---

src/App.tsx
src/feature/landing/index.tsx
src/feature/landing/ui/FilterSection.tsx
src/feature/landing/ui/LandingPostView.tsx
src/pages/LandingPage.tsx
src/shared/auth/CompanyProtectedRoute.tsx
src/shared/auth/ReissueRoute.tsx

- 랜딩페이지에서 자동 로그인이 가능하도록 설정합니다.
- 뒤로가기 시 랜딩페에지의 무한 로딩이 나타나는 버그를 수정하였습니다.
- useRef 사용 시 useEffect를 사용하여 순수성을 지킬 수 있도록 설정하였습니다. 

🐛 토큰 만료 시 랜딩페이지 무한로딩 버그 해결

---

src/api/apis/localServer/apis.ts
src/feature/auth/service/authService.ts
src/feature/auth/ui/findAccount/FindIdForm.tsx
src/feature/auth/ui/findAccount/FindPasswordForm.tsx

- UI만 존재하는 아이디/비번 찾기 페이지에 API를 연결하여 기능을 완성합니다.
- 비밀번호 찾기의 경우 Figma 디자인과 다르게 스누메일 입력란만 존재하도록 수정하였습니다.

✨ 아이디/비번 찾기 기능 API 연결

---

src/components/modal/CancelCoffeeChatDeleteModal.tsx
src/feature/coffeeChat/ui/CoffeeChatDetailView.tsx

💄 유저 커피챗 상세 페이지 ui 세팅

---

src/shared/auth/ApplicantProtectedRoute.tsx

- role context가 머지 과정에서 잘못 선언된 부분을 수정합니다.

🚑 role context가 잘못 지정된 부분 수정

---

src/App.tsx
src/entities/route.ts
src/feature/auth/presentation/authInputPresentation.ts
src/feature/auth/ui/findAccount/FindPasswordForm.tsx
src/pages/ResetPasswordPage.tsx
src/shared/route/useRouteNavigation.ts

- 비밀번호 재발급 시 스누메일이 아닌 일반 메일로 입력합니다.
- 지원자뿐만 아니라 회사 회원 또한 비밀번호를 재발급 받을 수 있도록 합니다.
- UI에 디자인 시스템을 적용하는 작업은 #379 가 완료된 이후에 수행할 예정입니다.

✨ 비밀번호 재발급 시 일반 메일 입력

---

src/api/apis/localServer/apis.ts
src/api/apis/localServer/schemas.ts
src/api/apis/utils/queryEncodeUtil.ts
src/entities/post.ts
src/feature/landing/ui/FilterSection.tsx
src/feature/landing/ui/LandingPostView.tsx
src/feature/post/service/postService.ts
src/feature/ventureCapital/service/ventureCapitalService.ts
src/feature/ventureCapital/ui/MyPostList.tsx
src/pages/LandingPage.tsx

- query parameter에 인코딩을 적용하였습니다. service 레이어가 아니라 api 모듈에서 인코딩을 수행하도록 수정하였습니다.
- 기존 filterElement라는 네이밍이 모호하여 postFilter로 네이밍을 변경하였습니다. 또한 status 보다는 모집 여부를 표현하기에는 employing이 더 적합하다고 생각하여 변수명을 수정하였습니다.
- 기존 filterElement의 타입이 모호하여 타입을 좁혀놓았습니다. (string -> JobMinorCategory)

🐛 query parameter 인코딩 적용

---

src/components/checkbox/CheckboxWithLabel.tsx
src/components/label/LabelContainer.tsx
src/feature/post/presentation/postFormPresentation.ts
src/feature/post/presentation/postInputPresentation.ts
src/feature/post/ui/form/CreatePostForm.tsx
src/feature/post/ui/form/fields/EmploymentEndDateField.tsx
src/feature/post/ui/form/fields/SalaryField.tsx
src/pages/CreatePostPage.tsx

- 피그마에 맞게 공고 작성 페이지 UI를 변경하였습니다.
- API는 확정 후 수정될 예정입니다.

✨ 공고 작성 페이지 UI 수정사항 반영

---

src/App.tsx
src/entities/route.ts
src/feature/auth/service/authService.ts
src/feature/coffeeChat/ui/mypage/common/NoCoffeeChat.tsx
src/feature/post/presentation/postFormPresentation.ts
src/feature/post/ui/common/PostCard.tsx
src/feature/post/ui/detail/PostDetailView.tsx
src/feature/post/ui/form/PatchPostForm.tsx
src/pages/CompanyMyPage.tsx
src/pages/CreatePostPage.tsx
src/shared/auth/AuthAdminSwitchRoute.tsx
src/shared/auth/ProtectedRoute.tsx
src/shared/context/RoleContext.ts
src/shared/context/UserContext.ts
src/shared/role/state.ts
src/shared/route/useRouteNavigation.ts

- 회사 계정으로 로그인 시 userId를 Role과 함께 context로 저장하도록 하였습니다.
- 해당 userId를 공고 상세페이지에서 체크해서 본인 회사가 작성한 공고인지 확인합니다.
- 공고 수정 페이지 UI를 생성하고 상세페이지와 연결했습니다(현재는 location.state 사용, 추후 변경 예정).

✨ 인턴 공고 수정 페이지 생성 및 연결

---

package.json
src/App.tsx
src/api/apis/localServer/apis.ts
src/api/apis/localServer/schemas.ts
src/entities/company.ts
src/entities/link.ts
src/entities/post.ts
src/entities/route.ts
src/feature/applicant/presentation/applicantFormPresentation.ts
src/feature/applicant/presentation/applicantInputPresentation.ts
src/feature/applicant/service/applicantService.ts
src/feature/applicant/ui/form/CreateProfileForm.tsx
src/feature/company/presentation/companyFormPresentation.ts
src/feature/company/presentation/companyInputPresentation.ts
src/feature/company/service/companyService.ts
src/feature/company/ui/form/CreateCompanyForm.tsx
src/feature/company/ui/form/fields/LocationField.tsx
src/feature/post/service/postService.ts
src/feature/post/ui/form/fields/JobCategoryField.tsx
src/mocks/applicant/schemas.ts
src/pages/CreateCompanyPage.tsx
src/util/format.ts
src/util/postFormatFunctions.ts
yarn.lock

💄 회사 생성 폼 UI 생성

---

src/api/apis/localServer/apis.ts
src/api/apis/localServer/schemas.ts
src/components/button/LinkButton.tsx
src/components/thumbnail/ThumbnailWithPresignedUrl.tsx
src/entities/post.ts
src/feature/company/service/companyService.ts
src/feature/company/ui/mypage/CompanyProfile.tsx
src/feature/company/ui/mypage/NoCompanyProfile.tsx
src/feature/company/ui/mypage/SkeletonCompanyProfile.tsx
src/feature/post/ui/detail/PostDetailView.tsx
src/mocks/auth/data.ts
src/mocks/auth/handlers.ts
src/mocks/auth/resolvers.ts
src/mocks/auth/schemas.ts
src/mocks/company/data.ts
src/mocks/company/handlers.ts
src/mocks/company/resolvers.ts
src/mocks/company/schemas.ts
src/mocks/handlers.ts

💄 회사 프로필 페이지 UI 작성

---

src/api/apis/localServer/schemas.ts
src/entities/post.ts
src/feature/company/ui/form/CreateCompanyForm.tsx
src/feature/company/ui/mypage/CompanyProfileInfo.tsx
src/feature/post/ui/detail/PostDetailView.tsx
src/mocks/company/schemas.ts

- vcName과 vcRecommendation을 선택 입력 사항으로 변경하였습니다.

👽️ vcName, vcRecommendation을 nullable하도록 처리

---

src/components/ui/layout.tsx
src/feature/applicant/ui/modal/WithdrawModal.tsx
src/feature/applicant/ui/mypage/ApplicantProfileView.tsx
src/feature/auth/service/authService.ts
src/feature/company/ui/mypage/CompanyProfileView.tsx

- 일반 유저에 대한 탈퇴 기능을 추가하였습니다.
- 탈퇴 전 모달을 띄워 탈퇴 여부를 확인합니다.

✨ 탈퇴 기능 추가

---

.github/workflows/deploy-dev.yml

- 개발 환경 배포를 추가하였습니다.
- mocksericeworker.js가 삭제되지 않는 문제를 수정하였습니다.
- CI 테스트를 위해 머지 이후 리뷰를 받도록 하겠습니다.

💚 개발 환경 배포 추가

---

.github/workflows/deploy-dev.yml
src/App.tsx
src/feature/coffeeChat/ui/detail/ApplicantCoffeeChatDetailView.tsx
src/feature/coffeeChat/ui/mypage/applicant/ApplicantCoffeeChatListView.tsx
src/feature/post/ui/common/PostCard.tsx
src/feature/post/ui/detail/PostDetailView.tsx
src/main.tsx
src/shared/context/EnvContext.ts

- 불필요한 BASE_URL 설정을 삭제합니다.
- 배포 환경 테스트를 위해 머지 이후 리뷰를 받습니다.

🐛 불필요한 API BASE URL 삭제

---

index.html

- GA 설정을 위한 스크립트를 삽입하였습니다.
- 이게 최선이라는 자신은 없긴 합니다.. 한번씩 리서치해보고 좋은 의견 있으면 알려주시면 감사하겠습니다

✨ Google Analytics 설정을 위한 스크립트 삽입

---

index.html

- locahost에서는 집계가 되지 않으나, dev 환경에서 집계되는 문제가 발생하여 도메인 가드를 추가하였습니다.

✨ GA 도메인 가드 추가

---

src/api/apis/localServer/schemas.ts
src/feature/company/ui/mypage/NoCreatedPosts.tsx
src/feature/post/ui/common/CompanyPostCard.tsx
src/feature/post/ui/common/PostCard.tsx
src/feature/post/ui/detail/PostDetailView.tsx
src/feature/post/ui/form/PatchPostForm.tsx
src/feature/post/ui/mypage/applicant/BookmarkListView.tsx
src/feature/post/ui/mypage/company/MyPostList.tsx
src/pages/CompanyMyPage.tsx
src/pages/CreatePostPage.tsx
src/util/postFormatFunctions.ts

- 변경된 API에 맞게 PostPathParams 수정
- 마감된 공고일 경우 수정 불가하게 변경
- 마감된 공고일 경우 모집완료로 표기되도록 변경
- 상세페이지 직군 포매팅
- 공고수정시 날짜 제대로 처리 안되는 오류 수정
- 작성된 공고 없을 시 ui 표시하도록 변경 (공고 없는 신규 회사 계정으로 테스트해봐야 할 듯합니다)

🐛 공고 관련 추가 수정사항들 반영

---

src/api/apis/localServer/apis.ts
src/api/apis/localServer/schemas.ts
src/feature/auth/presentation/authFormPresentation.ts
src/feature/auth/presentation/authInputPresentation.ts
src/feature/auth/service/authService.ts
src/feature/auth/ui/signUp/EmailVerifyForm.tsx

- 회원가입 시 successCode를 추가하였습니다.

👽️ 회원가입 시 successCode 추가

---

.env.dev
src/components/button/CoffeeChatButton.tsx
src/feature/coffeeChat/ui/mypage/company/CompanyCoffeeChatButton.tsx
src/feature/coffeeChat/ui/mypage/company/CompanyCoffeeChatButtonGroup.tsx
src/pages/CompanyMyPage.tsx

- 신청된 커피챗 탭에서 신청한 커피챗이 존재하지 않더라도 선택 버튼이 나타나는 오류를 해결했습니다

✨ 신청한 커피챗이 존재하지 않더라도 선택 버튼이 나타나는 오류 해결

---

src/App.tsx
src/feature/post/ui/detail/PostDetailView.tsx
src/feature/post/ui/modal/WriteCVModal.tsx
src/feature/post/ui/modal/WriteProfileModal.tsx
src/shared/auth/CoffeeChatAvailableProtectedRoute.tsx

- 프로필 및 CV 작성 유도 모달을 추가하였습니다.
- 프로필이 없는 유저가 url을 통해 커피챗 생성 페이지로 들어오는 경우를 방어하였습니다.

✨ 프로필 및 CV 작성 유도 모달 추가

---

src/components/field/MarkdownEditorField.tsx
src/feature/post/presentation/postInputPresentation.ts
src/feature/post/ui/form/CreatePostForm.tsx
src/feature/post/ui/form/PatchPostForm.tsx
src/feature/post/ui/form/fields/JobCategoryField.tsx

- 직군 선택 모달을 피그마와 동일한 UI를 갖도록 수정하였습니다.
- 마크다운 에디터에 placeholder 속성을 추가하였습니다.
- 직군 선택 모달
- 마크다운 에디터 placeholder

💄 직군 선택 모달 UI 피그마와 동일하게 수정

---

index.html

- 런칭 전까지 구글 서치 콘솔에 등록되는 것을 막아둡니다.

✨ 구글 서치로 검색 불가능하도록 설정

---

src/components/modal/CancelCheckModal.tsx
src/components/modal/CancelCoffeeChatCancelModal.tsx
src/components/modal/ClosePostModal.tsx
src/components/modal/ReSignInModal.tsx
src/components/modal/RewritePostModal.tsx
src/components/modal/SignInForBookmarkModal.tsx
src/components/modal/SignInForCoffeChatModal.tsx
src/components/modal/SignUpModal.tsx
src/components/modal/UpdateCoffeeChatStatusModal.tsx
src/components/ui/layout.tsx
src/feature/applicant/ui/modal/WithdrawModal.tsx
src/feature/auth/ui/signUp/RedirectSignInModal.tsx
src/feature/post/ui/modal/WriteCVModal.tsx
src/feature/post/ui/modal/WriteProfileModal.tsx
src/pages/ChangePasswordPage.tsx
src/pages/EmailVerifyPage.tsx
src/pages/ResetPasswordPage.tsx
src/pages/SignUpCompletePage.tsx
src/pages/SignUpPage.tsx

✨ 모달 피그마와 동일하게 반영

---

src/api/apis/localServer/schemas.ts
src/entities/post.ts
src/feature/post/service/postService.ts
src/feature/post/ui/landing/LandingPageView.tsx
src/feature/post/ui/landing/LandingPostView.tsx
src/feature/post/ui/landing/RolesFilter.tsx
src/mocks/post/schemas.ts
src/util/format.ts

- 직군 중 게임, AI, 인사를 추가하였습니다.
- 직군 필터 적용 시 positions 대신 roles를 사용하도록 설정하였습니다.

👽️ 직군 내용 변경 대응 및 필터 이름 변경 적용

---

src/components/ui/tabs.tsx
src/feature/coffeeChat/ui/mypage/company/CompanyCoffeeChatButton.tsx
src/feature/coffeeChat/ui/mypage/company/CompanyCoffeeChatButtonGroup.tsx
src/pages/ApplicantMyPage.tsx
src/pages/CompanyMyPage.tsx

💄 마이페이지 탭 반응형 적용

---

src/feature/post/ui/mypage/applicant/BookmarkListView.tsx
src/feature/post/ui/mypage/applicant/NoBookmarkedPosts.tsx

- 구직자 관심 공고 없을 때 나타나는 뷰 생성하였습니다

✨ 관심 공고 없을 때 나타나는 뷰 생성

---

.github/workflows/deploy-client.yml
.github/workflows/deploy-dev.yml

💚 배포 인프라 변경에 따른 CD Workflow 수정

---

.github/workflows/deploy-client.yml
.github/workflows/deploy-dev.yml

💚 버킷 이름 변경

---

src/components/button/DownloadButtonWithPresignedUrl.tsx
src/feature/applicant/ui/mypage/ApplicantProfileInfo.tsx
src/feature/coffeeChat/ui/detail/ApplicantInfoForCoffeeChat.tsx
src/feature/company/ui/mypage/CompanyProfileInfo.tsx
src/feature/post/ui/detail/PostDetailView.tsx
src/feature/post/ui/detail/SkeletonPostDetailView.tsx
src/shared/file/hooks.ts

- 파일 다운로드 시 이름을 자연스럽게 변경하였습니다.
이력서: 이름_이력서
포트폴리오: 이름_포트폴리오
회사 소개자료: 회사명_소개자료
- IR Deck 대신 회사소개자료라는 워딩을 사용하였습니다.

🐛 파일 다운로드 시 이름 변경

---

src/components/ui/calendar.tsx
src/feature/post/ui/form/CreatePostForm.tsx
src/feature/post/ui/form/fields/EmploymentEndDateField.tsx
src/feature/post/ui/form/fields/JobCategoryField.tsx
src/feature/post/ui/form/fields/SalaryField.tsx
src/pages/CreatePostPage.tsx

- 공고 생성 시 팝업에 의해 반응형이 깨지는 문제를 해결하였습니다.
- 캘린더 variant에 small을 추가하였습니다.

🐛 팝업 모달에 대한 반응형 추가

---

.env.dev
.env.prod
index.html
vite.config.ts

🚑 vite proxy에서 변경된 와플 인프라 적용

---

src/api/apis/localServer/schemas.ts
src/components/modal/ClosePostModal.tsx
src/entities/route.ts
src/feature/post/presentation/postFormPresentation.ts
src/feature/post/ui/detail/PostDetailView.tsx
src/feature/post/ui/form/CreatePostForm.tsx
src/feature/post/ui/form/PatchPostForm.tsx
src/feature/post/ui/form/fields/SalaryField.tsx

- 공고 마감 모달 닫기 애니메이션 적용
- 공고 수정 시 채용/급여 체크박스 반영
- 공고 상세 페이지에서 급여 정보 표기
- 월급 단위 만원으로 변경

🐛공고 관련 QA 반영

---

src/components/ui/layout.tsx
src/components/ui/tabs.tsx
src/feature/auth/ui/fields/PasswordConfirmField.tsx
src/feature/auth/ui/fields/PasswordField.tsx
src/feature/auth/ui/fields/PasswordFieldWithDetailedError.tsx
src/feature/auth/ui/signUp/EmailVerifyForm.tsx

* 비밀번호 필드 eye_icon 겹친 이슈 수정
* modal 반응형
* 로그인, 회원가입 반응형
alt="Screenshot 2025-05-09 at 3 23 10 PM" src="https://github.com/user-attachments/assets/1aa097b0-55bc-4933-96c1-d0ff14e9c941" />

✨ 로그인, 회원가입, 모달 반응형 적용

---

src/components/button/CoffeeChatButton.tsx
src/components/ui/tabs.tsx
src/feature/coffeeChat/ui/mypage/common/CoffeeChatNumberBadge.tsx
src/feature/coffeeChat/ui/mypage/company/CompanyCoffeeChatButtonGroup.tsx
src/pages/CompanyMyPage.tsx
src/pages/SignInPage.tsx

- 회사회원 나에게 신청된 커피챗 탭에서 ‘선택하기’ 누를 시 탭 overflow UI 수정
- CoffeeChatNumberBadge 버튼 관련 경고 수정

✨ 회사회원 나에게 신청된 커피챗 탭에서 ‘선택하기’ 누를 시 탭 overflow 및  경고 해결

---

package.json
src/components/field/MarkdownEditorField.tsx
src/components/ui/markdown-preview.tsx
src/index.css
tsconfig.json
yarn.lock

- 더 UI가 예쁜 마크다운 에디터로 변경하였습니다. (Toast UI)
- 이미지 삽입 버튼을 삭제하였습니다.

💄 마크다운 에디터 변경 및 이미지 업로드 기능 삭제

---

src/components/ui/popover.tsx
src/feature/coffeeChat/ui/detail/ApplicantCoffeeChatDetailView.tsx
src/feature/coffeeChat/ui/detail/CompanyCoffeeChatDetailView.tsx
src/feature/post/ui/detail/PostDetailView.tsx
src/feature/post/ui/landing/FilterSection.tsx

* 구직자 커피챗 신청직후 공고상세 에서 목록으로 하면 신청서 작성으로 가는 오류 해결
* 커피챗 상세보기에서 공고로 가는 링크 추가
* Landing Page 필터시 적용 누를때 모달 닫히기

🐛  메인페이지 및 커피챗 오류

---

src/components/field/ImageField.tsx

- 프로필 작성/수정 시 프로필 이미지 버튼 hover 시 pointer로 변경

🐛 프로필 작성/수정 시 프로필 이미지 버튼 hover 시 pointer로 변경

---

src/components/modal/UpdateCoffeeChatStatusModal.tsx
src/feature/coffeeChat/ui/detail/CompanyCoffeeChatDetailView.tsx

- 커피챗 상세 페이지에서 성사 및 거절 시 모달 추가했습니다

✨ 커피챗 상세 페이지에서 성사 및 거절 시 모달 추가

---

src/components/field/TextareaField.tsx
src/feature/coffeeChat/ui/form/CreateCoffeeChatForm.tsx
src/pages/CreateCoffeeChatPage.tsx

💄 구직자 커피챗 신청서 style 수정

---

index.html
src/feature/auth/presentation/authInputPresentation.ts
src/feature/auth/ui/fields/PasswordFieldWithDetailedError.tsx

- 연속된 문자열에 동일 문자 연속 포함 (e.g. aaaa, 1111) 시키도록 수정

연속된 문자열에 동일 문자 연속 포함 (e.g. aaaa, 1111)

---

index.html
src/feature/post/presentation/postInputPresentation.ts
src/feature/post/ui/form/CreatePostForm.tsx
src/feature/post/ui/form/PatchPostForm.tsx

🐛 공고 제목 글자수 제한 100자 로 변경

---

src/feature/applicant/ui/form/CreateProfileForm.tsx
src/feature/coffeeChat/ui/form/CreateCoffeeChatForm.tsx
src/feature/company/presentation/companyFormPresentation.ts
src/feature/company/ui/form/CreateCompanyForm.tsx
src/feature/post/ui/form/CreatePostForm.tsx

- 제출하기 시 폼에서 에러가 발생하면 전체 최하단에 메세지 나타나도록 수정
- 학생 프로필 작성 시 학과 관련 에러 메세지 내용 변경
- 회사 전체 인원수가 0명인 경우 에러로 처리

🐛 폼 관련 에러 메세지 내용 및 배치 수정

---

src/feature/post/ui/landing/FilterSection.tsx

💄 필터 중 공고 등록순으로 이름 변경

---

index.html
src/feature/post/ui/landing/FilterSection.tsx

🔥 noindex 제거

---

src/feature/post/ui/common/PostCard.tsx
src/feature/post/ui/detail/PostDetailView.tsx
src/feature/post/ui/landing/LandingPostView.tsx

- 공고 메인 페이지 및 상세 페이지 북마크 적용 시 optimistic updates
- TODO 로 되어있던 toast 추가

🐛 북마크 적용 시 Optimistic Updates

---

src/feature/auth/service/authService.ts
src/feature/auth/ui/signUp/EmailVerifyForm.tsx

- 메일 인증을 시도하기 전 해당 메일이 중복되었는지 체크하는 로직을 추가합니다.

🐛 메일 중복 인증 확인 로직 추가

---

src/components/ui/pagination.tsx
src/feature/post/ui/landing/LandingPostView.tsx
src/feature/post/ui/landing/PaginationBar.tsx
src/mocks/post/data.ts
src/mocks/post/handlers.ts
src/mocks/post/resolvers.ts
src/mocks/post/schemas.ts
src/pages/LandingPage.tsx

- 페이지네이션 시 쿼리파라미터에 의해 올바른 숫자의 버튼이 선택 상태에 있도록 설정합니다.
- 그룹 버튼에서 이전과 다음 버튼이 disable되도록 설정합니다.

🐛 페이지네이션 시 쿼리 파라미터 반영 및 disble 적용

---

src/components/footer/Footer.tsx

- 푸터에 버그 제보를 위한 구글폼 링크를 추가하였습니다.

✨ 푸터에 버그 제보용 구글폼 추가

---

src/entities/post.ts
src/feature/post/ui/common/PostCard.tsx
src/feature/post/ui/detail/PostDetailView.tsx
src/feature/post/ui/landing/LandingPostView.tsx

- 머지 이후 타입 정의에 의한 ci 터짐을 수정하였습니다.

🚑 post 관련 타입 지정

---

src/feature/post/ui/detail/PostDetailView.tsx

🐛 모바일에서 외부 링크 부분 스타일링 깨지는 부분 수정
